[package]
name = "kai_sav"
edition = "2024"

[dependencies]
whusdce = { local = "../../../_vendor/coins/whUSDCe" }
whusdte = { local = "../../../_vendor/coins/whUSDTe" }
scallop_protocol = { local = "../../../_vendor/Scallop/protocol-v10", rename-from = "protocol" }
scallop_pool = { local = "../../../_vendor/Scallop/spool-v2", rename-from = "spool" }
kai_ywhusdte_ysui = { local = "../vault-token-init/kai-ywhusdte-ysui" }
access_management = { local = "../../../access-management" }
kai_leverage = { local = "../../leverage/core" }
rate_limiter = { local = "../../../rate-limiter" }
