[package]
name = "klsp_sui"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Krešimir Klas (kklas@kunalabs.io)"]

[dependencies]
kai_leverage = { local = "../../core" }
klsp_init = { local = "../core" }
