[package]
name = "paused_klsp_suiusdt"
edition = "2024"

[dependencies]
kai_leverage = { local = "../../core" }
klsp_init = { local = "../core" }
suiusdt = { local = "../../../../_vendor/coins/suiUSDT" }
