[package]
name = "klsp_usdc"
edition = "2024"
license = "Apache 2.0"
authors = ["Krešimir Klas (kklas@kunalabs.io)"]

[dependencies]
kai_leverage = { local = "../../core" }
klsp_init = { local = "../core" }
usdc = { local = "../../../../_vendor/coins/USDC" }
