[package]
name = "klsp_init"
edition = "2024"
license = "Apache 2.0"
authors = ["Krešimir Klas (kklas@kunalabs.io)"]

[dependencies]
kai_leverage = { local = "../../core" }
access_management = { local = "../../../../access-management" }
