[package]
name = "kai_leverage"
license = "Apache 2.0"
authors = ["Krešimir Klas (kklas@kunalabs.io)"]
edition = "2024"

[dependencies]
access_management = { local = "../../../access-management" }
cetus_clmm = { local = "../../../_vendor/Cetus/clmm-v13" }
integer_mate = { local = "../../../_vendor/Cetus/integer-mate-v7", override = true }
pyth = { local = "../../../_vendor/Pyth/core-v2" }
bluefin_spot = { local = "../../../_vendor/Bluefin/spot-v17" }
rate_limiter = { local = "../../../rate-limiter" }

whusdce = { local = "../../../_vendor/coins/whUSDCe", modes = ["test"] }
whusdte = { local = "../../../_vendor/coins/whUSDTe", modes = ["test"] }
usdc = { local = "../../../_vendor/coins/USDC", modes = ["test"] }
suiusdt = { local = "../../../_vendor/coins/suiUSDT", modes = ["test"] }
usdy = { local = "../../../_vendor/coins/USDY", modes = ["test"] }
deep = { local = "../../../_vendor/coins/DEEP", modes = ["test"] }
wal = { local = "../../../_vendor/coins/WAL", modes = ["test"] }
lbtc = { local = "../../../_vendor/coins/LBTC", modes = ["test"] }
wbtc = { local = "../../../_vendor/coins/wBTC", modes = ["test"] }
xbtc = { local = "../../../_vendor/coins/xBTC", modes = ["test"] }
